### ISSUE TITLE
Show ticket's name before it is validated

### ISSUE THREAD

**Issue by fynngodau** [pretix/pretixscan-android#11]
Currently, when a ticket is scanned and the network connection is bad, the app will only show what ticket has been scanned after it has been verified with the server. This can lead to a situation where e.g. cashdesk angels have to wait until the ticket is validated before they can prepare the goodies to hand out. If the query fails, the ticket has to be scanned again, possibly after enabling offline mode by hand.

That's why I think there should be a mode that immediately shows the scanned ticket but indicates that it is still being checked in in the background. Once verified it should display checkmark / warning sign as normal. If validation fails, the app should temporarily switch to offline mode until internet connectivity is restored.

**Comment by raphaelm** [comment]
It is intentional that the switch between online and offline mode is not automatic. The two modes have very different trade-offs between security and reliability/performance, and I believe this decision needs to be done carefully. If the network connection is bad, one should switch to offline mode, but only *after* considering what that means, i.e. that a ticket could theoretically be scanned twice.

Therefore, I believe a "hybrid" mode would be a lot of effort for little gain and would lead to lots of unwanted results, e.g. if data changes online.
