### ISSUE TITLE
Camera noise is recognized as barcode

### ISSUE THREAD

**Issue by DHD-Harper** [pretix/pretixscan-android#110]
While pretix only generates QR codes, pretixscan can read a wide range of codes, including simple barcodes. I have observed that codes are supposedly read in the camera noise alone, which leads to many error entries in the event log.

I suggest limiting the app to scanning QR codes.

**Comment by pc-coholic** [comment]
That was actually one of my very first PRs for pretixSCAN - but we decided against this: https://github.com/pretix/pretixscan-android/pull/25

Since we do not have any knowledge which cursed barcode formats others might still be using, there is no good way of selecting which barcode types are acceptable.

**Comment by DHD-Harper** [comment]
I suspect that the vast majority of users of this app will only scan QR codes. So the default should be that only QR codes are accepted. You can then provide a setting that also allows other options.
