### ISSUE TITLE
"The server returned an invalid response" on Pretix-Installation behind Nginx.

### ISSUE THREAD

**Issue by Bapf** [pretix/pretixscan-android#66]
I have a self hosted Pretix installation behind an Nginx as reverse proxy.
Both the web access an the iOS scan app work fine, but when I try to connect this app i get an "The server returned an invalid response" error.
- Pointing the dns entry directly to the pretix server works, so the culprit is definitely the reverse proxy.
- I don't even see any requests on the vhost log on the Nginx. So I suspect the error already happens when the ssl negotiations are taking place.
Which further information could be helpful?

**Comment by raphaelm** [comment]
Do you see a request on any other vhost / nginx log?

**Comment by Bapf** [comment]
If you ask this way ... yes: In the permanentban.log. (I forgot to mention it's an Nginx running inside an OPNsense and I only checked the normal vhost-logs so far.)
Interestingly only the POST-requests from the android app land there / trigger this. Not requests from the web or the iOS app ...

**Comment by brightcolor** [comment]
@Bapf 
I have exactly the same problem - also behind a nginx on OPNsense. The requests are also in my autoblock.log - were you able to solve the problem and if so, how?

**Comment by brightcolor** [comment]
@Bapf I spoke to one of my DevOps. He put me on the trail of the solution. The problem is the bot protection of the OPNsense nginx plugin. I deactivated it in the corresponding HTTP Server in the advanced view. Now Android works and the Windows client also works.

Now I am looking for a way to whitelist the user agent (okhttp/4.9.3 eu.pretix.pretixscan.droid/2.10.3).
