### ISSUE TITLE
Updated version on Google Play, but no release, nor a prerelease on F-Droid

### ISSUE THREAD

**Issue by marcusmueller** [pretix/pretixscan-android#72]
As we're using old phones without google accounts for registration desks, using the Google Play Store is a large additional effort (we'd need to create a new Google user and complete Google setup on each phone) compared to installing the APK (e.g. as downloaded from f-droid and then sideloaded).

Would it be possible to declare the current state of affairs a release, tag it and push it to f-droid?

**Comment by raphaelm** [comment]
We tag a release regularly, as you can see here:
https://github.com/pretix/pretixscan-android/tags

We also publish official APKs here:
https://marketplace.pretix.eu/products/pretixscan-android/versions

And we even offer a fdroid clone that can install these binaries:
https://marketplace.pretix.eu/products/marketplace-client-android/

We don't publish to the official fdroid repo, and we never have. Someone else has, but we have no control over the builds there.

**Comment by licaon-kter** [comment]
Updated it, not an easy task to rebuild all the binaries :( https://gitlab.com/fdroid/fdroiddata/-/blob/2a730bf8be59afdf266816913611b07b5216cfbe/metadata/eu.pretix.pretixscan.droid.yml#L173-L252

Anyway, @raphaelm your repo index has an issue, "suggestedVersionCode" in the v1 index is an int and not a string like it is there for historical reasons so when adding your repo in current 1.17 will fail: `Unexpected JSON Token blahblah`.

**Comment by raphaelm** [comment]
> Updated it, not an easy task to rebuild all the binaries :(

Oh wow. I'm surprised this requires so much work, because this is the actual script we use to build our official releases and it's much… simpler: https://github.com/pretix/pretixscan-android/blob/master/.gitlab-ci.yml

For a variety of reasons, we are not really sad that our apps aren't updated on F-Droid. Support-wise non-official builds are annoying, because we don't control how they are built exactly and we can't issue hotfix releases for very urgent issues on our own timeline (in the event industry, every once in a while, a fix is within-the-hour-urgent). Many of these would change with reproducible builds, i.e. having them on F-Droid with our signatures, which I would personally like a lot, but lack the time to look into it deeper.

**For the moment**, 

> Anyway, @raphaelm your repo index has an issue, "suggestedVersionCode" in the v1 index is an int and not a string like it is there for historical reasons so when adding your repo in current 1.17 will fail: Unexpected JSON Token blahblah.

Thanks! I've created a PR for it: https://github.com/pretix/plum/pull/3

I have "update our client app" on my to-do list anyways, then I'll test it in more detail.

**Comment by licaon-kter** [comment]
> Oh wow. I'm surprised this requires so much work, because this is the actual script we use to build our official releases and it's much… simpler:

Built from untrusted (by F-Droid) maven repos like:
* https://maven.pkg.github.com/Digitaler-Impfnachweis/covpass-android
* https://maven.pkg.github.com/ehn-dcc-development/
* http://raw.github.com/saki4510t/libcommon/master/repository/

and prebuilt binary .aar's like [this](https://github.com/pretix/libpretixui-android/tree/74117fb37cab52df5edc0cb3383ea0211c684dfd/android-libserenegiantcommon) and [that](https://github.com/pretix/libpretixui-android/tree/74117fb37cab52df5edc0cb3383ea0211c684dfd/android-libusbcameracommon) and [the other](https://github.com/pretix/libpretixui-android/tree/74117fb37cab52df5edc0cb3383ea0211c684dfd/android-libuvccamera)

... that won't fly with F-Droid :)

**Comment by raphaelm** [comment]
Fair enough :) Maybe we'll get rid of the covpass stuff again, not sure yet. The libcommon stuff ist… wild, but USB camera support is just really bad on Android :(
